### ISSUE TITLE
Suggestion to use Settings API

### ISSUE THREAD

**Issue by psifertex** [Martyx00/ghinja#1]
Rather than a local metadata store, might I recommend using the Settings API? The advantage is if the plugin is removed / reinstalled, the previous settings will be maintained. Here's an example plugin that uses the Settings API:

https://github.com/withzombies/bnil-graph/blob/master/__init__.py#L21-L48

Likewise, you might consider using something like `Path(user_plugin_path()) / ".." / "ghinja_projects" ` as a good folder versus `~/.ghinja_projects` for better cross-platform portability.  (IE, `.dot` files not being standard on windows)

**Comment by Martyx00** [comment]
Thanks! Both suggestions will be taken into account for next release along other improvments and fixes. Unfortunately I dont have ETA on that as the development is done in my free time only.

**Comment by psifertex** [comment]
No worries, totally understand. I might throw a PR together too if I get some time knowing you're amenable.

**Comment by Martyx00** [comment]
Both suggestions and the raw image for the plugin manager were addressed by ab02653dc383b3cea91dfce4eb9d20f136972f5b. I will try to implement couple more fixes before making the 0.2 release (or 1.0 if I will feel confident enough).
