### ISSUE TITLE
Not able to enable: Qt 6 must import PySide6 instead of PySide2

### ISSUE THREAD

**Issue by TheREK3R** [Martyx00/ghinja#11]
I'm not sure if this is an issue on my end but I am fully updated in Binja 3.0.3233 and ghidra. My platform is windows. This was working for me a few months ago. 

Does anyone recognize this error?

**Comment by Martyx00** [comment]
Hello, this is addressed with version 1.9: https://github.com/Martyx00/ghinja/releases/tag/1.9
