### ISSUE TITLE
OSX: Welcome dialog 'open file'  is without the title

### ISSUE THREAD

**Issue by trib0r3** [Martyx00/ghinja#3]
Hello,

After installation the open file dialog is popping up. Unfortunately on OSX it don't have any title, so it is not clear what file should be picked without checking it in the source code.

My suggestion is to replace the open file window with message box asking the user to set correct path for ghidra headless in settings

**Comment by Martyx00** [comment]
Hmm, I don't have any official way to test things on OSX so thanks for that! I will think of something that will be appropriate for all platforms.

**Comment by Martyx00** [comment]
I have updated the code to always show a message box prompt that will notify user that the following file chooser dialog is actually asking for a path to `analyzeHeadless` (https://github.com/Martyx00/ghinja/commit/2f41be3341de105b5b57293c09b15419a20cc872). Thanks for spotting this!
