### ISSUE TITLE
Stuck at Decompiler running

### ISSUE THREAD

**Issue by Sn0wfl4keXD** [Martyx00/ghinja#5]
Hey  so i might just be stupid right now but i dont get it to work.
So sorry if i waste your time with that.

in my Settings.json it looks like that
```json
	"ghinja" : 
	{
		"ghidra_install_path" : "/home/sn0wfl4ke/ghidra/support/analyzeHeadless"
	}
```

Now when  I want to Decompile a small Programm which is instalty there inside Ghidra
it just stuck me in Decompiler running....

I am pretty sure i did sth wrong with the installation or that i  am missing sth kinda noob at this xD

my os i use it on is btw linux

thx already ^^

**Comment by Martyx00** [comment]
Hello,
I will have a look at that. Can you in the meantime see if `/home/sn0wfl4ke/.binaryninja/ghinja_projects/<filename>/` contains decompiled source files?

**Comment by Martyx00** [comment]
I think I identified the issue, the approach that I am using does not work for Ghidra 9.2 for some reason. I will have to investigate this and adjust the Java script. In the meantime, you can make this work by using Ghidra 9.1.2.

**Comment by Martyx00** [comment]
I had a brief look and it seems that things have changed in Ghidra 9.2. You can track progress of this issue here: https://github.com/NationalSecurityAgency/ghidra/issues/2562
Sorry for the inconvenience, I recommend using 9.1.2 for the time being.

**Comment by Sn0wfl4keXD** [comment]
thanks i will get the 9.1.2

Also Folders exist in here ```/home/sn0wfl4ke/.binaryninja/ghinja_projects/<filename>/```
But those are empty

**Comment by Martyx00** [comment]
You can try to clone the current latest version of the repository (https://github.com/Martyx00/ghinja/commit/20cf4747c03e869083b74785fb47e0cb6b06c0b2) and see if it works now. I have tested it on Windows and it was working just fine. I am not sure when exactly I will also have time to test it on Linux but it will be in couple days latest. When confirmed I will publish a new release. Before trying again make sure that you remove the folders from `ghinja_projects` just to be sure.

**Comment by Sn0wfl4keXD** [comment]
I will test it later today for sure   i let u know if it worked ^^
Thanks for your effort

**Comment by Sn0wfl4keXD** [comment]
Ok i tried it on Linux.
I can confirm  it works

**Comment by Martyx00** [comment]
Just published a new release. Thanks for reporting the issue. Spread the word if you like the plugin!
